---
language: python
services: docker

env:
  global:
    - ROLE_NAME: influxdb
  matrix:
    - MOLECULE_DISTRO: ubuntu2004

install:
  # Install test dependencies.
  - pip install --upgrade pip
  - pip install wheel
  - pip install 'molecule[docker]' docker ansible ansible-lint flake8

before_script:
  # Use actual Ansible Galaxy role name for the project directory.
  - cd ../
  - mv ansible-$ROLE_NAME heytrav.$ROLE_NAME
  - cd heytrav.$ROLE_NAME

script:
  # Run tests.
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
