- name: Import package download url
  include_vars:
    file: vars/centos.yml
    name: source

- name: Install influxdb
  yum:
    name: "{{ influxdb_url }}"
    state: present
  notify:
    - influxdb started
