- name: Install some python dependencies
  pip:
    name:
      - requests
      - influxdb
    state: present

- name: Start influxd
  service:
    name: influxd
    state: started

- name: Wait for a connection on influxdb port
  wait_for:
    host: localhost
    port: 8086

- name: Add admin user to influx
  influxdb_user:
    admin: yes
    user_name: "{{ influxdb_admin_user }}"
    user_password: "{{ influxdb_admin_user_password }}"
    state: present

- name: Set authentication over HTTP/HTTPs
  replace:
    regexp: '^(\s+auth-enabled\s+=\s+).*'
    replace:  '\1{{ influxdb_http_auth_enabled | lower }}'
    path: /etc/influxdb/influxdb.conf
  notify: influxdb restarted
