---
- name: Install some python dependencies
  pip:
    name:
      - requests
      - influxdb
      - pexpect
    state: present

- name: Start influxd
  systemd:
    name: influxd
    state: started

- name: Wait for a connection on influxdb port
  wait_for:
    host: localhost
    port: 8086


- name: Run initial setup to create admin user
  expect:
    command: influx setup
    responses:
      '.*primary\susername': "{{ influxdb_admin_user }}"
      '.*type\syour\spassword.*': "{{ influxdb_admin_user_password }}"
      '.*organization.*': "{{ influxdb_admin_organization }}"
      '.*bucket.*': "{{ influxdb_primary_bucket }}"
      '.*retention.*': "{{ influxdb_retention_period }}"
      '.*Confirm.*': "y"
    creates: /root/.influxdbv2/configs
  no_log: true
