---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: centos7
    image: percygrunwald/docker-centos7-ansible
    privileged: false
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    pre_build_image: true
    environment:
      container: docker
  - name: bionic
    image: percygrunwald/docker-ubuntu1804-ansible
    privileged: false
    pre_build_image: true
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    environment:
      container: docker
  - name: xenial
    image: percygrunwald/docker-ubuntu1604-ansible
    privileged: false
    pre_build_image: true
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    environment:
      container: docker
provisioner:
  name: ansible
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
  options:
    verbose: true
