---

default_platform: &platform
  privileged: true
  tmpfs:
    - /run
    - /tmp
  volumes:
    - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
  command: /lib/systemd/systemd
  tty: true
  environment:
    container: docker


dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos8
    image: centos:8
    <<: *platform
  - name: centos7
    image: geerlingguy/docker-centos7-ansible
    <<: *platform
  - name: bionic
    image: geerlingguy/docker-ubuntu1804-ansible:latest
    <<: *platform
  - name: focal
    image: geerlingguy/docker-ubuntu2004-ansible:latest
    <<: *platform
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
